// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// Export file: ../Assets/Scripts/behaviac/exported/behaviac_generated/behaviors/generated_behaviors.cs
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;

namespace behaviac
{
	// Source file: HoverBotBT

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_HoverBotBT_node3 : behaviac.Condition
	{
		public Condition_bt_HoverBotBT_node3()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			bool opl = ((HoverBotAgent)pAgent).HasTarget();
			bool opr = false;
			bool op = opl == opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_HoverBotBT_node10 : behaviac.Action
	{
		public Action_bt_HoverBotBT_node10()
		{
			this.m_resultOption = EBTStatus.BT_INVALID;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.EBTStatus result = ((HoverBotAgent)pAgent).DoPatrol();
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_HoverBotBT_node1 : behaviac.Condition
	{
		public Condition_bt_HoverBotBT_node1()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			float opl = ((HoverBotAgent)pAgent).GetTargetDist();
			float opr = 10f;
			bool op = opl > opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_HoverBotBT_node8 : behaviac.Action
	{
		public Action_bt_HoverBotBT_node8()
		{
			this.m_resultOption = EBTStatus.BT_INVALID;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.EBTStatus result = ((HoverBotAgent)pAgent).DoChase();
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_HoverBotBT_node9 : behaviac.Condition
	{
		public Condition_bt_HoverBotBT_node9()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			float opl = ((HoverBotAgent)pAgent).GetTargetDist();
			float opr = 3f;
			bool op = opl > opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_HoverBotBT_node14 : behaviac.Action
	{
		public Action_bt_HoverBotBT_node14()
		{
			this.m_resultOption = EBTStatus.BT_INVALID;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.EBTStatus result = ((HoverBotAgent)pAgent).DoChase();
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_HoverBotBT_node13 : behaviac.Action
	{
		public Action_bt_HoverBotBT_node13()
		{
			this.m_resultOption = EBTStatus.BT_INVALID;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.EBTStatus result = ((HoverBotAgent)pAgent).DoAttack();
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_HoverBotBT_node11 : behaviac.Action
	{
		public Action_bt_HoverBotBT_node11()
		{
			this.m_resultOption = EBTStatus.BT_INVALID;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.EBTStatus result = ((HoverBotAgent)pAgent).StopChase();
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_HoverBotBT_node12 : behaviac.Action
	{
		public Action_bt_HoverBotBT_node12()
		{
			this.m_resultOption = EBTStatus.BT_INVALID;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.EBTStatus result = ((HoverBotAgent)pAgent).DoAttack();
			return result;
		}
	}

	public static class bt_HoverBotBT
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("HoverBotBT");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("HoverBotAgent");
#endif
			// children
			{
				Selector node0 = new Selector();
				node0.SetClassNameString("Selector");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("HoverBotAgent");
#endif
				bt.AddChild(node0);
				{
					Sequence node2 = new Sequence();
					node2.SetClassNameString("Sequence");
					node2.SetId(2);
#if !BEHAVIAC_RELEASE
					node2.SetAgentType("HoverBotAgent");
#endif
					node0.AddChild(node2);
					{
						Condition_bt_HoverBotBT_node3 node3 = new Condition_bt_HoverBotBT_node3();
						node3.SetClassNameString("Condition");
						node3.SetId(3);
#if !BEHAVIAC_RELEASE
						node3.SetAgentType("HoverBotAgent");
#endif
						node2.AddChild(node3);
						node2.SetHasEvents(node2.HasEvents() | node3.HasEvents());
					}
					{
						Action_bt_HoverBotBT_node10 node10 = new Action_bt_HoverBotBT_node10();
						node10.SetClassNameString("Action");
						node10.SetId(10);
#if !BEHAVIAC_RELEASE
						node10.SetAgentType("HoverBotAgent");
#endif
						node2.AddChild(node10);
						node2.SetHasEvents(node2.HasEvents() | node10.HasEvents());
					}
					node0.SetHasEvents(node0.HasEvents() | node2.HasEvents());
				}
				{
					Selector node4 = new Selector();
					node4.SetClassNameString("Selector");
					node4.SetId(4);
#if !BEHAVIAC_RELEASE
					node4.SetAgentType("HoverBotAgent");
#endif
					node0.AddChild(node4);
					{
						Sequence node7 = new Sequence();
						node7.SetClassNameString("Sequence");
						node7.SetId(7);
#if !BEHAVIAC_RELEASE
						node7.SetAgentType("HoverBotAgent");
#endif
						node4.AddChild(node7);
						{
							Condition_bt_HoverBotBT_node1 node1 = new Condition_bt_HoverBotBT_node1();
							node1.SetClassNameString("Condition");
							node1.SetId(1);
#if !BEHAVIAC_RELEASE
							node1.SetAgentType("HoverBotAgent");
#endif
							node7.AddChild(node1);
							node7.SetHasEvents(node7.HasEvents() | node1.HasEvents());
						}
						{
							Action_bt_HoverBotBT_node8 node8 = new Action_bt_HoverBotBT_node8();
							node8.SetClassNameString("Action");
							node8.SetId(8);
#if !BEHAVIAC_RELEASE
							node8.SetAgentType("HoverBotAgent");
#endif
							node7.AddChild(node8);
							node7.SetHasEvents(node7.HasEvents() | node8.HasEvents());
						}
						node4.SetHasEvents(node4.HasEvents() | node7.HasEvents());
					}
					{
						Sequence node5 = new Sequence();
						node5.SetClassNameString("Sequence");
						node5.SetId(5);
#if !BEHAVIAC_RELEASE
						node5.SetAgentType("HoverBotAgent");
#endif
						node4.AddChild(node5);
						{
							Condition_bt_HoverBotBT_node9 node9 = new Condition_bt_HoverBotBT_node9();
							node9.SetClassNameString("Condition");
							node9.SetId(9);
#if !BEHAVIAC_RELEASE
							node9.SetAgentType("HoverBotAgent");
#endif
							node5.AddChild(node9);
							node5.SetHasEvents(node5.HasEvents() | node9.HasEvents());
						}
						{
							Action_bt_HoverBotBT_node14 node14 = new Action_bt_HoverBotBT_node14();
							node14.SetClassNameString("Action");
							node14.SetId(14);
#if !BEHAVIAC_RELEASE
							node14.SetAgentType("HoverBotAgent");
#endif
							node5.AddChild(node14);
							node5.SetHasEvents(node5.HasEvents() | node14.HasEvents());
						}
						{
							Action_bt_HoverBotBT_node13 node13 = new Action_bt_HoverBotBT_node13();
							node13.SetClassNameString("Action");
							node13.SetId(13);
#if !BEHAVIAC_RELEASE
							node13.SetAgentType("HoverBotAgent");
#endif
							node5.AddChild(node13);
							node5.SetHasEvents(node5.HasEvents() | node13.HasEvents());
						}
						node4.SetHasEvents(node4.HasEvents() | node5.HasEvents());
					}
					{
						Sequence node6 = new Sequence();
						node6.SetClassNameString("Sequence");
						node6.SetId(6);
#if !BEHAVIAC_RELEASE
						node6.SetAgentType("HoverBotAgent");
#endif
						node4.AddChild(node6);
						{
							Action_bt_HoverBotBT_node11 node11 = new Action_bt_HoverBotBT_node11();
							node11.SetClassNameString("Action");
							node11.SetId(11);
#if !BEHAVIAC_RELEASE
							node11.SetAgentType("HoverBotAgent");
#endif
							node6.AddChild(node11);
							node6.SetHasEvents(node6.HasEvents() | node11.HasEvents());
						}
						{
							Action_bt_HoverBotBT_node12 node12 = new Action_bt_HoverBotBT_node12();
							node12.SetClassNameString("Action");
							node12.SetId(12);
#if !BEHAVIAC_RELEASE
							node12.SetAgentType("HoverBotAgent");
#endif
							node6.AddChild(node12);
							node6.SetHasEvents(node6.HasEvents() | node12.HasEvents());
						}
						node4.SetHasEvents(node4.HasEvents() | node6.HasEvents());
					}
					node0.SetHasEvents(node0.HasEvents() | node4.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

	// Source file: HoverBotBTBasic

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_HoverBotBTBasic_node1 : behaviac.Action
	{
		public Action_bt_HoverBotBTBasic_node1()
		{
			this.m_resultOption = EBTStatus.BT_INVALID;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.EBTStatus result = ((HoverBotAgent)pAgent).DoPatrol();
			return result;
		}
	}

	public static class bt_HoverBotBTBasic
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("HoverBotBTBasic");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("HoverBotAgent");
#endif
			// children
			{
				Selector node0 = new Selector();
				node0.SetClassNameString("Selector");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("HoverBotAgent");
#endif
				bt.AddChild(node0);
				{
					Action_bt_HoverBotBTBasic_node1 node1 = new Action_bt_HoverBotBTBasic_node1();
					node1.SetClassNameString("Action");
					node1.SetId(1);
#if !BEHAVIAC_RELEASE
					node1.SetAgentType("HoverBotAgent");
#endif
					node0.AddChild(node1);
					node0.SetHasEvents(node0.HasEvents() | node1.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

}
